name: CI/CD Pipeline de Infraestrutura - IIS

on:
  workflow_dispatch:
    inputs:
      nome_site:
        description: 'Nome do Site no IIS (Ex: MeuSistema (Homologação))'
        required: true
        type: string

      nome_apppool:
        description: 'Nome do App Pool (Ex: AppPool_MeuSistema)'
        required: true
        type: string

      caminho_fisico:
        description: 'Caminho Físico (Ex: D:\MeuSistema)'
        required: true
        type: string
        default: 'D:\auto-iis-test'

      versao_dotnet:
        description: 'Versão do .NET CLR'
        required: true
        type: choice
        options:
          - 'v4.0'
          - 'v2.0'
          - 'No Managed Code'

      modo_pipeline:
        description: 'Modo do Pipeline'
        required: true
        type: choice
        options:
          - 'Integrated'
          - 'Classic'

      identidade_pool:
        description: 'Identidade do App Pool'
        required: true
        type: choice
        options:
          - 'DOMINIO\AppPoolUser'
          - 'ApplicationPoolIdentity'

      host_name:
        description: 'Hostname (Ex: homolog.exemplo.com.br)'
        required: true
        type: string

      protocolo:
        description: 'Protocolo'
        required: true
        type: choice
        options:
          - 'HTTP'
          - 'HTTPS'
          - 'HTTP + HTTPS'

      ip_binding:
        description: 'IP do Binding (Ex: 192.168.1.10)'
        required: true
        default: '192.168.1.10'
        type: string

      certificado_nome:
        description: 'Nome do certificado HTTPS (Ex: *.exemplo.com.br)'
        required: false
        default: '*.exemplo.com.br'
        type: string

jobs:
  provision-infrastructure:
    runs-on: [self-hosted, default-runner]

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Verificar arquivo de provisionamento
        shell: powershell
        run: |
          Write-Host "Arquivo utilizado:"
          Get-Item ".\scripts\Provision-IIS.ps1" | Select-Object FullName, Length, LastWriteTime

      - name: Executar Provisionamento do IIS
        shell: powershell
        env:
          POOL_PASSWORD: ${{ secrets.POOL_PASSWORD }}
        run: |
          .\scripts\Provision-IIS.ps1 `
            -SiteName "${{ inputs.nome_site }}" `
            -AppPoolName "${{ inputs.nome_apppool }}" `
            -PhysicalPath "${{ inputs.caminho_fisico }}" `
            -DotNetVersion "${{ inputs.versao_dotnet }}" `
            -PipelineMode "${{ inputs.modo_pipeline }}" `
            -AppPoolIdentity "${{ inputs.identidade_pool }}" `
            -HostName "${{ inputs.host_name }}" `
            -Protocol "${{ inputs.protocolo }}" `
            -BindingIP "${{ inputs.ip_binding }}" `
            -CertificateName "${{ inputs.certificado_nome }}"
